### PR TITLE
Fix broken TOC (sidebar) when main content is expanded then collapsed

### LINKED ISSUE #372: Broken TOC when showing more Used by
ezgif com-optimize

### PR DESCRIPTION
**Pull request by outdoor2kode**
Fixes https://github.com/WordPress/wporg-developer/issues/372

This PR fixes the broken TOC. Changes:

**Sidebar Repositioning Logic:**

Implemented a check within the ResizeObserver to detect if the sidebar is positioned at its bottommost location (is-bottom-sidebar class). On detection, the sidebar's position is dynamically adjusted to align correctly with the resized content.

**Scroll Position Adjustment:**

Following the repositioning of the sidebar, the scroll position is then altered.
This adjustment ensures that the sidebar remains visible to the user.

## Screenshot

https://d.pr/i/O1iLY7

### CODE REVIEW

File: mu-plugins/blocks/sidebar-container/src/view.js [hunk 1]
```diff
@@ -136,6 +136,31 @@ function init() {
 			container.classList.add( 'is-fixed-sidebar' );
 			onScroll(); // Run once to avoid footer collisions on load (ex, when linked to #reply-title).
 			window.addEventListener( 'scroll', onScroll );
+
+			// eslint-disable-next-line no-undef
+			const observer = new ResizeObserver( () => {
```
Comment (adamwoodnz) [inline mu-plugins/blocks/sidebar-container/src/view.js]:
```suggestion
			const observer = new window.ResizeObserver( () => {
```

File: mu-plugins/blocks/sidebar-container/src/view.js [hunk 2]
```diff
@@ -136,6 +136,31 @@ function init() {
...
+				// When the mainEl includes class "is-bottom-sidebar" and undergoes resizes,
+				// it means that the sidebar is positioned at its bottommost location.
+				// In this case, It is necessary to manually trigger the resize
+				// under the condition (footerStart - gap < sidebarBottom) to adjust the position appropriately.
+				// Otherwise, the sidebar will remain at the bottom of the page, leading to a broken page layout.
```
Comment (adamwoodnz) [inline mu-plugins/blocks/sidebar-container/src/view.js]:
```suggestion
				// If the sidebar is positioned at the bottom and mainEl resizes,
				// it will remain fixed at the previous bottom position, leading to a broken page layout.
				// In this case manually trigger the scroll handler to reposition.
```

**Review by adamwoodnz — COMMENTED** [review]
Works for me, nice!

Couple of minor suggestions inline.

File: mu-plugins/blocks/sidebar-container/src/view.js (hunk 2 above)
Comment (outdoor2kode) [reply mu-plugins/blocks/sidebar-container/src/view.js]: Thanks!

**Review by adamwoodnz — APPROVED** [review]
